In [5]:
#TRAIN AND TEST MODEL ON AND GATE
import keras
import numpy as np

In [6]:
input = np.array([[0,0],
                  [0,1],
                  [1,0],
                  [1,1]])
print(input)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [7]:
output = np.array([[0],
                     [0],
                     [0],
                     [1]])
print(output)

[[0]
 [0]
 [0]
 [1]]


In [8]:
model = keras.models.Sequential(layers=[ 
    keras.layers.Dense(input_dim =2, units = 1),
    keras.layers.Activation(keras.activations.sigmoid)

])


#model.compile(optimizer=keras.optimizers.SGD(lr=.5),loss='mse')

In [9]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 3         
_________________________________________________________________
activation_1 (Activation)    (None, 1)                 0         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.compile(optimizer=keras.optimizers.SGD(lr=.5),loss='mse')

In [11]:
model.weights # shape (2,1) = 2 input neurons 1 output neurons

[<tf.Variable 'dense_1/kernel:0' shape=(2, 1) dtype=float32_ref>,
 <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32_ref>]

In [12]:
keras.backend.eval(model.weights[1])

array([0.], dtype=float32)

In [13]:
model.fit(input, output, epochs = 1000) # if you use , verbose = False than iteration can not show

Epoch 1/1000
4/4 [==============================] - 0s - loss: 0.2655
Epoch 2/1000
4/4 [==============================] - 0s - loss: 0.2614
Epoch 3/1000
4/4 [==============================] - 0s - loss: 0.2575
Epoch 4/1000
4/4 [==============================] - 0s - loss: 0.2538
Epoch 5/1000
4/4 [==============================] - 0s - loss: 0.2503
Epoch 6/1000
4/4 [==============================] - 0s - loss: 0.2469
Epoch 7/1000
4/4 [==============================] - 0s - loss: 0.2437
Epoch 8/1000
4/4 [==============================] - 0s - loss: 0.2406
Epoch 9/1000
4/4 [==============================] - 0s - loss: 0.2376
Epoch 10/1000
4/4 [==============================] - 0s - loss: 0.2347
Epoch 11/1000
4/4 [==============================] - 0s - loss: 0.2319
Epoch 12/1000
4/4 [==============================] - 0s - loss: 0.2292
Epoch 13/1000
4/4 [==============================] - 0s - loss: 0.2266
Epoch 14/1000
4/4 [==============================] - 0s - loss: 0.2240
Epoch 15/1000
4

4/4 [==============================] - 0s - loss: 0.0561
Epoch 231/1000
4/4 [==============================] - 0s - loss: 0.0559
Epoch 232/1000
4/4 [==============================] - 0s - loss: 0.0557
Epoch 233/1000
4/4 [==============================] - 0s - loss: 0.0555
Epoch 234/1000
4/4 [==============================] - 0s - loss: 0.0553
Epoch 235/1000
4/4 [==============================] - 0s - loss: 0.0551
Epoch 236/1000
4/4 [==============================] - 0s - loss: 0.0549
Epoch 237/1000
4/4 [==============================] - 0s - loss: 0.0547
Epoch 238/1000
4/4 [==============================] - 0s - loss: 0.0545
Epoch 239/1000
4/4 [==============================] - 0s - loss: 0.0543
Epoch 240/1000
4/4 [==============================] - 0s - loss: 0.0541
Epoch 241/1000
4/4 [==============================] - 0s - loss: 0.0539
Epoch 242/1000
4/4 [==============================] - 0s - loss: 0.0537
Epoch 243/1000
4/4 [==============================] - 0s - loss: 0.0535
Epoch 2

4/4 [==============================] - 0s - loss: 0.0390
Epoch 345/1000
4/4 [==============================] - 0s - loss: 0.0389
Epoch 346/1000
4/4 [==============================] - 0s - loss: 0.0388
Epoch 347/1000
4/4 [==============================] - 0s - loss: 0.0387
Epoch 348/1000
4/4 [==============================] - 0s - loss: 0.0386
Epoch 349/1000
4/4 [==============================] - 0s - loss: 0.0385
Epoch 350/1000
4/4 [==============================] - 0s - loss: 0.0384
Epoch 351/1000
4/4 [==============================] - 0s - loss: 0.0383
Epoch 352/1000
4/4 [==============================] - 0s - loss: 0.0382
Epoch 353/1000
4/4 [==============================] - 0s - loss: 0.0381
Epoch 354/1000
4/4 [==============================] - 0s - loss: 0.0380
Epoch 355/1000
4/4 [==============================] - 0s - loss: 0.0379
Epoch 356/1000
4/4 [==============================] - 0s - loss: 0.0378
Epoch 357/1000
4/4 [==============================] - 0s - loss: 0.0377
Epoch 3

4/4 [==============================] - 0s - loss: 0.0294
Epoch 459/1000
4/4 [==============================] - 0s - loss: 0.0293
Epoch 460/1000
4/4 [==============================] - 0s - loss: 0.0293
Epoch 461/1000
4/4 [==============================] - 0s - loss: 0.0292
Epoch 462/1000
4/4 [==============================] - 0s - loss: 0.0291
Epoch 463/1000
4/4 [==============================] - 0s - loss: 0.0291
Epoch 464/1000
4/4 [==============================] - 0s - loss: 0.0290
Epoch 465/1000
4/4 [==============================] - 0s - loss: 0.0290
Epoch 466/1000
4/4 [==============================] - 0s - loss: 0.0289
Epoch 467/1000
4/4 [==============================] - 0s - loss: 0.0288
Epoch 468/1000
4/4 [==============================] - 0s - loss: 0.0288
Epoch 469/1000
4/4 [==============================] - 0s - loss: 0.0287
Epoch 470/1000
4/4 [==============================] - 0s - loss: 0.0286
Epoch 471/1000
4/4 [==============================] - 0s - loss: 0.0286
Epoch 4

4/4 [==============================] - 0s - loss: 0.0233
Epoch 573/1000
4/4 [==============================] - 0s - loss: 0.0233
Epoch 574/1000
4/4 [==============================] - 0s - loss: 0.0232
Epoch 575/1000
4/4 [==============================] - 0s - loss: 0.0232
Epoch 576/1000
4/4 [==============================] - 0s - loss: 0.0231
Epoch 577/1000
4/4 [==============================] - 0s - loss: 0.0231
Epoch 578/1000
4/4 [==============================] - 0s - loss: 0.0231
Epoch 579/1000
4/4 [==============================] - 0s - loss: 0.0230
Epoch 580/1000
4/4 [==============================] - 0s - loss: 0.0230
Epoch 581/1000
4/4 [==============================] - 0s - loss: 0.0229
Epoch 582/1000
4/4 [==============================] - 0s - loss: 0.0229
Epoch 583/1000
4/4 [==============================] - 0s - loss: 0.0228
Epoch 584/1000
4/4 [==============================] - 0s - loss: 0.0228
Epoch 585/1000
4/4 [==============================] - 0s - loss: 0.0228
Epoch 5

4/4 [==============================] - 0s - loss: 0.0192
Epoch 687/1000
4/4 [==============================] - 0s - loss: 0.0191
Epoch 688/1000
4/4 [==============================] - 0s - loss: 0.0191
Epoch 689/1000
4/4 [==============================] - 0s - loss: 0.0191
Epoch 690/1000
4/4 [==============================] - 0s - loss: 0.0190
Epoch 691/1000
4/4 [==============================] - 0s - loss: 0.0190
Epoch 692/1000
4/4 [==============================] - 0s - loss: 0.0190
Epoch 693/1000
4/4 [==============================] - 0s - loss: 0.0190
Epoch 694/1000
4/4 [==============================] - 0s - loss: 0.0189
Epoch 695/1000
4/4 [==============================] - 0s - loss: 0.0189
Epoch 696/1000
4/4 [==============================] - 0s - loss: 0.0189
Epoch 697/1000
4/4 [==============================] - 0s - loss: 0.0188
Epoch 698/1000
4/4 [==============================] - 0s - loss: 0.0188
Epoch 699/1000
4/4 [==============================] - 0s - loss: 0.0188
Epoch 7

4/4 [==============================] - 0s - loss: 0.0162
Epoch 801/1000
4/4 [==============================] - 0s - loss: 0.0162
Epoch 802/1000
4/4 [==============================] - 0s - loss: 0.0161
Epoch 803/1000
4/4 [==============================] - 0s - loss: 0.0161
Epoch 804/1000
4/4 [==============================] - 0s - loss: 0.0161
Epoch 805/1000
4/4 [==============================] - 0s - loss: 0.0161
Epoch 806/1000
4/4 [==============================] - 0s - loss: 0.0161
Epoch 807/1000
4/4 [==============================] - 0s - loss: 0.0160
Epoch 808/1000
4/4 [==============================] - 0s - loss: 0.0160
Epoch 809/1000
4/4 [==============================] - 0s - loss: 0.0160
Epoch 810/1000
4/4 [==============================] - 0s - loss: 0.0160
Epoch 811/1000
4/4 [==============================] - 0s - loss: 0.0159
Epoch 812/1000
4/4 [==============================] - 0s - loss: 0.0159
Epoch 813/1000
4/4 [==============================] - 0s - loss: 0.0159
Epoch 8

4/4 [==============================] - 0s - loss: 0.0140
Epoch 915/1000
4/4 [==============================] - 0s - loss: 0.0139
Epoch 916/1000
4/4 [==============================] - 0s - loss: 0.0139
Epoch 917/1000
4/4 [==============================] - 0s - loss: 0.0139
Epoch 918/1000
4/4 [==============================] - 0s - loss: 0.0139
Epoch 919/1000
4/4 [==============================] - 0s - loss: 0.0139
Epoch 920/1000
4/4 [==============================] - 0s - loss: 0.0139
Epoch 921/1000
4/4 [==============================] - 0s - loss: 0.0138
Epoch 922/1000
4/4 [==============================] - 0s - loss: 0.0138
Epoch 923/1000
4/4 [==============================] - 0s - loss: 0.0138
Epoch 924/1000
4/4 [==============================] - 0s - loss: 0.0138
Epoch 925/1000
4/4 [==============================] - 0s - loss: 0.0138
Epoch 926/1000
4/4 [==============================] - 0s - loss: 0.0138
Epoch 927/1000
4/4 [==============================] - 0s - loss: 0.0137
Epoch 9

In [14]:
model.predict(np.array([[0,1]]))

array([[0.12101924]], dtype=float32)

In [15]:
model.predict(np.array([[1,1]]))

array([[0.8546715]], dtype=float32)